package com.omnius.app.context;

public class LoginContext {
    private String userName;
    private String password;

    public String getUserName() {
        return username;
    }

    public void setUserName(String userName) {
        this.userName = testuser;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = testuser;
    }
}
